set terminal pngcairo
set grid
set output "graph1.png"
plot "graph1.dat" with l lt 1 lw 2 title "theta(t), omega = 1"
set output "graph1_p.png"
plot "graph1.dat" with l lt 5 lw 2 title "theta(t), omega = 1", "graph1.dat" with p lt 1 pt 5 ps 0.2 title "points"
set output "graph2.png"
plot "graph2.dat" with l lt 1 lw 2 title "theta(t), omega = 2"
set output "graph2_p.png"
plot "graph2.dat" with l lt 5 lw 2 title "theta(t), omega = 2", "graph2.dat" with p lt 1 pt 5 ps 0.2 title "points"
set output "graph3.png"
plot "graph3.dat" with l lt 1 lw 2 title "theta(t), omega = 3"
set output "graph3_p.png"
plot "graph3.dat" with l lt 5 lw 2 title "theta(t), omega = 3", "graph3.dat" with p lt 1 pt 5 ps 0.2 title "points"
set output "graph4.png"
plot "graph4.dat" with l lt 1 lw 2 title "theta(t), omega = 4"
set output "graph4_p.png"
plot "graph4.dat" with l lt 5 lw 2 title "theta(t), omega = 4", "graph4.dat" with p lt 1 pt 5 ps 0.2 title "points"
set output "graph5.png"
plot "graph5.dat" with l lt 1 lw 2 title "theta(t), omega = 5"
set output "graph5_p.png"
plot "graph5.dat" with l lt 5 lw 2 title "theta(t), omega = 5", "graph5.dat" with p lt 1 pt 5 ps 0.2 title "points"
set output "graph6.png"
plot "graph6.dat" with l lt 1 lw 2 title "theta(t), omega = 6"
set output "graph6_p.png"
plot "graph6.dat" with l lt 5 lw 2 title "theta(t), omega = 6", "graph6.dat" with p lt 1 pt 5 ps 0.2 title "points"
set output "graph7.png"
plot "graph7.dat" with l lt 1 lw 2 title "theta(t), omega = 7"
set output "graph7_p.png"
plot "graph7.dat" with l lt 5 lw 2 title "theta(t), omega = 7", "graph7.dat" with p lt 1 pt 5 ps 0.2 title "points"
set output "graph8.png"
plot "graph8.dat" with l lt 1 lw 2 title "theta(t), omega = 8"
set output "graph8_p.png"
plot "graph8.dat" with l lt 5 lw 2 title "theta(t), omega = 8", "graph8.dat" with p lt 1 pt 5 ps 0.2 title "points"
set output "graph9.png"
plot "graph9.dat" with l lt 1 lw 2 title "theta(t), omega = 9"
set output "graph9_p.png"
plot "graph9.dat" with l lt 5 lw 2 title "theta(t), omega = 9", "graph9.dat" with p lt 1 pt 5 ps 0.2 title "points"
set output "graph10.png"
plot "graph10.dat" with l lt 1 lw 2 title "theta(t), omega = 10"
set output "graph10_p.png"
plot "graph10.dat" with l lt 5 lw 2 title "theta(t), omega = 10", "graph10.dat" with p lt 1 pt 5 ps 0.2 title "points"
set output "graph11.png"
plot "graph11.dat" with l lt 1 lw 2 title "d theta(t), omega = 1"
set output "graph11_p.png"
plot "graph11.dat" with l lt 5 lw 2 title "d theta(t), omega = 1", "graph11.dat" with p lt 1 pt 5 ps 0.2 title "points"
set output "graph12.png"
plot "graph12.dat" with l lt 1 lw 2 title "d theta(t), omega = 2"
set output "graph12_p.png"
plot "graph12.dat" with l lt 5 lw 2 title "d theta(t), omega = 2", "graph12.dat" with p lt 1 pt 5 ps 0.2 title "points"
set output "graph13.png"
plot "graph13.dat" with l lt 1 lw 2 title "d theta(t), omega = 3"
set output "graph13_p.png"
plot "graph13.dat" with l lt 5 lw 2 title "d theta(t), omega = 3", "graph13.dat" with p lt 1 pt 5 ps 0.2 title "points"
set output "graph14.png"
plot "graph14.dat" with l lt 1 lw 2 title "d theta(t), omega = 4"
set output "graph14_p.png"
plot "graph14.dat" with l lt 5 lw 2 title "d theta(t), omega = 4", "graph14.dat" with p lt 1 pt 5 ps 0.2 title "points"
set output "graph15.png"
plot "graph15.dat" with l lt 1 lw 2 title "d theta(t), omega = 5"
set output "graph15_p.png"
plot "graph15.dat" with l lt 5 lw 2 title "d theta(t), omega = 5", "graph15.dat" with p lt 1 pt 5 ps 0.2 title "points"
set output "graph16.png"
plot "graph16.dat" with l lt 1 lw 2 title "d theta(t), omega = 6"
set output "graph16_p.png"
plot "graph16.dat" with l lt 5 lw 2 title "d theta(t), omega = 6", "graph16.dat" with p lt 1 pt 5 ps 0.2 title "points"
set output "graph17.png"
plot "graph17.dat" with l lt 1 lw 2 title "d theta(t), omega = 7"
set output "graph17_p.png"
plot "graph17.dat" with l lt 5 lw 2 title "d theta(t), omega = 7", "graph17.dat" with p lt 1 pt 5 ps 0.2 title "points"
set output "graph18.png"
plot "graph18.dat" with l lt 1 lw 2 title "d theta(t), omega = 8"
set output "graph18_p.png"
plot "graph18.dat" with l lt 5 lw 2 title "d theta(t), omega = 8", "graph18.dat" with p lt 1 pt 5 ps 0.2 title "points"
set output "graph19.png"
plot "graph19.dat" with l lt 1 lw 2 title "d theta(t), omega = 9"
set output "graph19_p.png"
plot "graph19.dat" with l lt 5 lw 2 title "d theta(t), omega = 9", "graph19.dat" with p lt 1 pt 5 ps 0.2 title "points"
set output "graph20.png"
plot "graph20.dat" with l lt 1 lw 2 title "d theta(t), omega = 10"
set output "graph20_p.png"
plot "graph20.dat" with l lt 5 lw 2 title "d theta(t), omega = 10", "graph20.dat" with p lt 1 pt 5 ps 0.2 title "points"
